# Generated by Django 5.0.2 on 2024-03-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='url',
            new_name='url_stub',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='date',
        ),
        migrations.AddField(
            model_name='projects',
            name='creation_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='project_subtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='update_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
