# Generated by Django 5.0.2 on 2024-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url_stub',
            field=models.CharField(max_length=100),
        ),
    ]
