# Generated by Django 5.0.2 on 2024-03-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_url_stub'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Local Train Schedule (Jba)',
                'verbose_name_plural': 'Local Train Schedule (Jba)',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='update_date',
            field=models.DateField(),
        ),
    ]
