# Generated by Django 5.0.2 on 2024-04-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_localtrainschedule_alter_projects_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.IntegerField(choices=[(1, 'Hiroki'), (2, 'Obitan'), (3, 'Jba')])),
            ],
            options={
                'verbose_name': 'Fish Feeding (Jba & Obitan)',
                'verbose_name_plural': 'Fish Feeding (Jba & Obitan)',
            },
        ),
        migrations.DeleteModel(
            name='LocalTrainSchedule',
        ),
    ]
