# Generated by Django 5.0.2 on 2024-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projects_user_projects_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishfeeding',
            name='person',
            field=models.IntegerField(choices=[(0, 'Nobody'), (1, 'Hiroki'), (2, 'Obitan'), (3, 'Jba')]),
        ),
    ]
