# Generated by Django 5.0.2 on 2024-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_fishfeeding_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishfeeding',
            name='fish_fed_person',
            field=models.IntegerField(choices=[(0, '無'), (1, 'ダダ'), (2, 'オビたん'), (3, 'ジェイミー'), (9, '不明')]),
        ),
        migrations.AlterField(
            model_name='fishfeeding',
            name='tank_cleaned_person',
            field=models.IntegerField(choices=[(0, '無'), (1, 'ダダ'), (2, 'オビたん'), (3, 'ジェイミー'), (9, '不明')]),
        ),
    ]
