# Generated by Django 5.0.2 on 2024-04-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_fishfeeding_fish_fed_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
